//! P-H2H W3 — the matched OUR-SIDE speed harness: per-stage line-recognition
//! timing for `tesseract-ocr`'s pure-Rust pipeline, on the SAME line crops the
//! quality harness (W2) and the CLI-side companion script
//! (`corpus/hiertext/run_cli_speed.py`) use, so the throughput/latency numbers
//! land on identical inputs. This file is OUR-SIDE ONLY — it never shells out
//! to the C++ `tesseract` CLI; the CLI-side timing is produced separately by
//! that companion Python script.
//!
//! Corpus: `corpus/hiertext/lines_manifest.jsonl` (generated by
//! `gen_hiertext_lines.py`, same schema the companion script reads: one JSON
//! object per line with at least a `"crop"` field, a path relative to
//! `corpus/hiertext/`) if it exists, else every `corpus/lines/*.pgm` fixture
//! (sorted, unfiltered — the SAME fallback glob the companion script uses),
//! so the two sides always see byte-identical inputs either way.
//!
//! Methodology: the model loads ONCE (its own cost reported separately as a
//! one-time "cold" figure); one untimed warm-up pass over the whole corpus;
//! then 3 timed full-corpus passes. Each reported stage total is
//! independently the MINIMUM across the 3 timed passes (the steadiest
//! reading per stage — see the report's own footnote for what that implies
//! about the displayed "end-to-end" total).
//!
//! ```sh
//! cargo run --release -p tesseract-ocr --example h2h_speed -- 100
//! python3 corpus/hiertext/run_cli_speed.py 100   # the matched CLI-side half
//! ```

use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};

use tesseract_core::DictLite;
use tesseract_ocr::{parse_pgm, prescale_grey_to_height, LstmRecognizer};
use tesseract_recognizer::{from_grey_pix, TRand};

/// Number of timed full-corpus passes; each reported stage keeps the minimum
/// total across these (the steadiest reading per stage).
const TIMED_PASSES: usize = 3;
/// Default cap on the number of line crops processed, overridable by the
/// first CLI argument (`h2h_speed -- <N>`), mirroring the companion CLI-side
/// script's `sys.argv[1]`.
const DEFAULT_CAP: usize = 100;

/// The corpus root, resolved relative to this crate's manifest dir — the same
/// convention `golden_bench.rs` uses.
fn corpus_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus")
}

/// Prints a diagnostic to stderr and exits 1. A benchmark that silently
/// produced a partial/misleading number would be worse than one that stops.
fn fail(context: &str, err: impl std::fmt::Display) -> ! {
    eprintln!("error: {context}: {err}");
    std::process::exit(1);
}

/// Hand-rolled extraction of one top-level string field from a single-line
/// JSON object (the `lines_manifest.jsonl` schema) — no JSON crate dependency
/// in this crate, so this is a tiny, purpose-built parser, not a general JSON
/// reader. Handles the escapes JSON allows inside a string value (`\"`, `\\`,
/// `\/`, `\n`, `\t`); anything else after a backslash is passed through raw.
/// Returns `None` if `key` is absent or its value isn't a quoted string.
fn extract_json_string_field(line: &str, key: &str) -> Option<String> {
    let pat = format!("\"{key}\"");
    let key_pos = line.find(&pat)?;
    let after_key = &line[key_pos + pat.len()..];
    let colon_pos = after_key.find(':')?;
    let after_colon = after_key[colon_pos + 1..].trim_start();
    let mut chars = after_colon.strip_prefix('"')?.chars();
    let mut out = String::new();
    loop {
        match chars.next()? {
            '"' => return Some(out),
            '\\' => match chars.next()? {
                '"' => out.push('"'),
                '\\' => out.push('\\'),
                '/' => out.push('/'),
                'n' => out.push('\n'),
                't' => out.push('\t'),
                other => out.push(other),
            },
            c => out.push(c),
        }
    }
}

/// Discover the line crops to benchmark and report which corpus was used.
/// Prefers the HierText manifest; falls back to the committed
/// `corpus/lines/*.pgm` fixtures (sorted, unfiltered — including the two
/// multi-line page fixtures `page_roomy.pgm`/`page_tight.pgm`, exactly as the
/// companion CLI-side script's fallback glob does) so a matched comparison
/// always has an input set to run against, and both sides see the same one.
fn discover_crops(root: &Path, cap: usize) -> (Vec<PathBuf>, &'static str) {
    let hiertext = root.join("hiertext");
    let manifest = hiertext.join("lines_manifest.jsonl");
    if let Ok(text) = std::fs::read_to_string(&manifest) {
        let mut crops = Vec::new();
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() {
                continue;
            }
            let Some(rel) = extract_json_string_field(line, "crop") else {
                continue;
            };
            let p = hiertext.join(rel);
            if p.exists() {
                crops.push(p);
            }
        }
        if !crops.is_empty() {
            crops.truncate(cap);
            return (crops, "hiertext lines_manifest");
        }
        // Manifest present but yielded nothing usable -- fall through to the
        // committed fixtures below, same as an absent manifest.
    }
    let lines_dir = root.join("lines");
    let mut crops: Vec<PathBuf> = std::fs::read_dir(&lines_dir)
        .unwrap_or_else(|e| fail(&format!("read_dir {}", lines_dir.display()), e))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("pgm"))
        .collect();
    crops.sort();
    crops.truncate(cap);
    (crops, "corpus/lines fallback")
}

/// `LSTMRecognizer::SetRandomSeed` (`lstmrecognizer.h:287-291`) replicated
/// from ONLY public state: [`LstmRecognizer::sample_iteration`] (a public
/// field) and the public [`TRand`] API. The real production path
/// (`recognize_image_file`/`recognize_grey_line`) seeds via the PRIVATE
/// `LstmRecognizer::seeded_randomizer`/`prepare_grid` helpers, which an
/// example cannot call — this function reproduces their documented formula
/// instead of asking for a new public accessor. See the report's footnote
/// for the (non-)consequence for timing.
fn seeded_rng(sample_iteration: i32) -> TRand {
    let seed = i64::from(sample_iteration).wrapping_mul(0x1000_0001) as u64;
    let mut rng = TRand::default();
    rng.set_seed(seed);
    rng.int_rand(); // the warm-up draw SetRandomSeed always performs
    rng
}

/// The stage boundaries timed for one line, one pass. `grid_to_text` already
/// includes `forward` internally (`LstmRecognizer::recognize_grid_with_dict`
/// = forward + dict beam) — the beam-only cost is derived later by subtraction.
struct StageTimes {
    parse: Duration,
    prescale: Duration,
    grid: Duration,
    forward: Duration,
    grid_to_text: Duration,
}

/// Run every stage for one line crop. Returns `None` when the line is
/// skipped: unreadable/unparsable, or — matching
/// `LstmRecognizer::recognize_grey_line`'s own guard — its pre-scaled width
/// falls below the network's `Network::x_scale_factor`, the transcribed
/// `Input::PrepareLSTMInputs` "Image too small to scale!!" gate. A skipped
/// line contributes to neither the stage totals nor the line count for that
/// pass, exactly as production drops it rather than crashing.
fn time_one_line(
    recognizer: &LstmRecognizer,
    dict: &DictLite,
    path: &Path,
    bytes: &[u8],
    target_h: usize,
    min_width: usize,
) -> Option<StageTimes> {
    let t0 = Instant::now();
    let (grey, w, h) = match parse_pgm(bytes) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("skip {}: parse_pgm: {e}", path.display());
            return None;
        }
    };
    let parse = t0.elapsed();

    let t0 = Instant::now();
    let (scaled, sw) = prescale_grey_to_height(&grey, w, h, target_h);
    let prescale = t0.elapsed();

    if sw < min_width || target_h < min_width {
        eprintln!(
            "skip {}: too small to recognize (sw={sw}, target_h={target_h}, min_width={min_width})",
            path.display()
        );
        return None;
    }

    let t0 = Instant::now();
    let mut rng = seeded_rng(recognizer.sample_iteration);
    let grid = from_grey_pix(&scaled, sw, target_h, target_h as i32, 0, &mut rng);
    let grid_time = t0.elapsed();

    let t0 = Instant::now();
    let mut rng = seeded_rng(recognizer.sample_iteration);
    let forward_result = recognizer.network.forward(&grid, &mut rng);
    let forward = t0.elapsed();
    if let Err(e) = forward_result {
        eprintln!("skip {}: network.forward: {e}", path.display());
        return None;
    }

    // codex P2: time the SAME dict-beam path the quality harness measures
    // (recognize_grey_line loads DictLite) and the CLI uses (default English
    // language data) — not the non-dict recognize_grid. The derived beam row
    // below is therefore the DICT beam, matching the compared configuration.
    let t0 = Instant::now();
    let mut rng = seeded_rng(recognizer.sample_iteration);
    let grid_to_text_result = recognizer.recognize_grid_with_dict(&grid, &mut rng, dict.clone());
    let grid_to_text = t0.elapsed();
    if let Err(e) = grid_to_text_result {
        eprintln!("skip {}: recognize_grid_with_dict: {e}", path.display());
        return None;
    }

    Some(StageTimes {
        parse,
        prescale,
        grid: grid_time,
        forward,
        grid_to_text,
    })
}

/// Accumulated stage totals over one full pass across the whole corpus.
#[derive(Default)]
struct PassTotals {
    parse: Duration,
    prescale: Duration,
    grid: Duration,
    forward: Duration,
    grid_to_text: Duration,
    lines_ok: usize,
}

impl PassTotals {
    fn add(&mut self, t: &StageTimes) {
        self.parse += t.parse;
        self.prescale += t.prescale;
        self.grid += t.grid;
        self.forward += t.forward;
        self.grid_to_text += t.grid_to_text;
        self.lines_ok += 1;
    }

    /// The DERIVED beam+extract+text total for this pass: `recognize_grid`
    /// time minus `network.forward` time (since `recognize_grid_with_dict` = forward +
    /// beam). `saturating_sub` guards the (unexpected) case where per-pass
    /// timing jitter makes the standalone `forward` call read slower than
    /// the `forward` folded inside `recognize_grid`.
    fn beam(&self) -> Duration {
        self.grid_to_text.saturating_sub(self.forward)
    }

    /// This pass's end-to-end total: `parse + prescale + grid + grid_to_text`
    /// (`grid_to_text` already includes `forward`, so it is not added again).
    fn end_to_end(&self) -> Duration {
        self.parse + self.prescale + self.grid + self.grid_to_text
    }
}

/// One full pass over every crop, in order. Used for both the untimed
/// warm-up and the timed passes — the exact same code path, so warm-up
/// actually warms what gets timed.
fn run_pass(
    recognizer: &LstmRecognizer,
    dict: &DictLite,
    crops: &[(PathBuf, Vec<u8>)],
    target_h: usize,
    min_width: usize,
) -> PassTotals {
    let mut totals = PassTotals::default();
    for (path, bytes) in crops {
        if let Some(t) = time_one_line(recognizer, dict, path, bytes, target_h, min_width) {
            totals.add(&t);
        }
    }
    totals
}

/// Peak resident set size (`VmHWM` in `/proc/self/status`, e.g. `"66048 kB"`),
/// or a diagnostic string when `/proc` isn't available on this platform.
fn peak_rss_kb() -> String {
    match std::fs::read_to_string("/proc/self/status") {
        Ok(status) => status
            .lines()
            .find_map(|l| l.strip_prefix("VmHWM:"))
            .map(str::trim)
            .map(str::to_string)
            .unwrap_or_else(|| "VmHWM not present in /proc/self/status".to_string()),
        Err(_) => "unavailable (/proc/self/status not readable)".to_string(),
    }
}

fn main() {
    let cap: usize = std::env::args()
        .nth(1)
        .and_then(|s| s.parse().ok())
        .unwrap_or(DEFAULT_CAP);

    let root = corpus_root();
    let model_dir = root.join("model");
    let lstm_path = model_dir.join("eng.lstm");
    let uni_path = model_dir.join("eng.lstm-unicharset");
    let rec_path = model_dir.join("eng.lstm-recoder");

    let lstm = std::fs::read(&lstm_path)
        .unwrap_or_else(|e| fail(&format!("read {}", lstm_path.display()), e));
    let uni = std::fs::read_to_string(&uni_path)
        .unwrap_or_else(|e| fail(&format!("read {}", uni_path.display()), e));
    let rec = std::fs::read(&rec_path)
        .unwrap_or_else(|e| fail(&format!("read {}", rec_path.display()), e));

    // COLD: the model-load cost, timed once, apart from every other stage.
    let load_t0 = Instant::now();
    let recognizer = LstmRecognizer::from_components(&lstm, &uni, &rec)
        .unwrap_or_else(|e| fail("LstmRecognizer::from_components", e));
    let load_cold = load_t0.elapsed();

    // codex P2: load the DAWGs so the timed path matches the quality harness's
    // dict-beam configuration (see time_one_line).
    let word = std::fs::read(model_dir.join("eng.lstm-word-dawg"))
        .unwrap_or_else(|e| fail("read eng.lstm-word-dawg", e));
    let punc = std::fs::read(model_dir.join("eng.lstm-punc-dawg"))
        .unwrap_or_else(|e| fail("read eng.lstm-punc-dawg", e));
    let number = std::fs::read(model_dir.join("eng.lstm-number-dawg"))
        .unwrap_or_else(|e| fail("read eng.lstm-number-dawg", e));
    let dict = DictLite::from_components(&word, &punc, &number)
        .unwrap_or_else(|e| fail("DictLite::from_components", e));

    let (crop_paths, corpus_source) = discover_crops(&root, cap);
    if crop_paths.is_empty() {
        fail(
            "discover_crops",
            "no line crops found (checked corpus/hiertext/lines_manifest.jsonl and corpus/lines/*.pgm)",
        );
    }

    // Pre-load every crop's bytes ONCE; the timed passes below only pay for
    // the recognition stages, never file IO.
    let crops: Vec<(PathBuf, Vec<u8>)> = crop_paths
        .into_iter()
        .map(|p| {
            let bytes =
                std::fs::read(&p).unwrap_or_else(|e| fail(&format!("read {}", p.display()), e));
            (p, bytes)
        })
        .collect();

    // prepare_grid's target height + min-width gate, reconstructed from
    // PUBLIC state only (Network::input_shape, Network::x_scale_factor) --
    // `prepare_grid`/`seeded_randomizer` themselves stay private; nothing was
    // made public to build this harness.
    let target_h = recognizer
        .network
        .input_shape
        .map_or(36, |s| s.height.max(1) as usize);
    let min_width = recognizer.network.x_scale_factor().max(1) as usize;

    eprintln!("corpus: {corpus_source} ({} crops, cap {cap})", crops.len());

    // One untimed warm-up pass over the whole corpus.
    run_pass(&recognizer, &dict, &crops, target_h, min_width);

    // TIMED_PASSES timed full-corpus passes.
    let passes: Vec<PassTotals> = (0..TIMED_PASSES)
        .map(|_| run_pass(&recognizer, &dict, &crops, target_h, min_width))
        .collect();

    // Per-stage MIN total across passes (the steadiest reading, independently
    // per stage -- see the report's footnote for what this means for the
    // displayed "end-to-end" total).
    let min_of = |f: fn(&PassTotals) -> Duration| -> Duration {
        passes.iter().map(f).min().unwrap_or_default()
    };
    let parse_min = min_of(|p| p.parse);
    let prescale_min = min_of(|p| p.prescale);
    let grid_min = min_of(|p| p.grid);
    let forward_min = min_of(|p| p.forward);
    let beam_min = passes
        .iter()
        .map(PassTotals::beam)
        .min()
        .unwrap_or_default();
    // Composed from the five independently-steadied minimums above (see the
    // footnote) rather than re-measured as one more call.
    let end_to_end_min = parse_min + prescale_min + grid_min + forward_min + beam_min;
    // Cross-check: the best SINGLE pass's own end-to-end total (no mixing of
    // stages across passes) -- quantifies how far the composed figure above
    // can drift from a real, internally-consistent pass.
    let best_single_pass_end_to_end = passes
        .iter()
        .map(PassTotals::end_to_end)
        .min()
        .unwrap_or_default();

    let lines_ok = passes.first().map_or(0, |p| p.lines_ok);
    let peak_rss = peak_rss_kb();

    let ms = |d: Duration| d.as_secs_f64() * 1000.0;
    let us_per_line = |d: Duration| {
        if lines_ok == 0 {
            0.0
        } else {
            d.as_secs_f64() * 1_000_000.0 / lines_ok as f64
        }
    };
    let pct = |d: Duration| {
        if end_to_end_min.is_zero() {
            0.0
        } else {
            d.as_secs_f64() / end_to_end_min.as_secs_f64() * 100.0
        }
    };

    println!("## h2h_speed — our-side per-stage line-recognition timing (tesseract-ocr)");
    println!();
    println!(
        "Corpus: {corpus_source} ({lines_ok} lines), single-threaded, release recommended (`cargo run --release -p tesseract-ocr --example h2h_speed -- {cap}`)."
    );
    println!(
        "CLI-side timing for the SAME crops is produced separately by `corpus/hiertext/run_cli_speed.py {cap}` — this report is OUR-SIDE ONLY."
    );
    println!();
    println!("| stage | total ms (min pass) | µs/line | % of end-to-end |");
    println!("|---|---|---|---|");
    println!(
        "| parse_pgm | {:.3} | {:.2} | {:.1} |",
        ms(parse_min),
        us_per_line(parse_min),
        pct(parse_min)
    );
    println!(
        "| prescale_grey_to_height | {:.3} | {:.2} | {:.1} |",
        ms(prescale_min),
        us_per_line(prescale_min),
        pct(prescale_min)
    );
    println!(
        "| from_grey_pix (grid build) | {:.3} | {:.2} | {:.1} |",
        ms(grid_min),
        us_per_line(grid_min),
        pct(grid_min)
    );
    println!(
        "| network.forward | {:.3} | {:.2} | {:.1} |",
        ms(forward_min),
        us_per_line(forward_min),
        pct(forward_min)
    );
    println!(
        "| beam + extract + text (derived) | {:.3} | {:.2} | {:.1} |",
        ms(beam_min),
        us_per_line(beam_min),
        pct(beam_min)
    );
    println!(
        "| **end-to-end (sum of rows above)** | {:.3} | {:.2} | 100.0 |",
        ms(end_to_end_min),
        us_per_line(end_to_end_min)
    );
    println!();
    println!("**Summary**");
    println!();
    println!("| metric | value |");
    println!("|---|---|");
    println!(
        "| lines/sec (end-to-end) | {:.2} |",
        if end_to_end_min.is_zero() {
            0.0
        } else {
            lines_ok as f64 / end_to_end_min.as_secs_f64()
        }
    );
    println!("| model load (cold, one-time) | {:.3} ms |", ms(load_cold));
    println!(
        "| single best pass, end-to-end (sanity check) | {:.3} ms |",
        ms(best_single_pass_end_to_end)
    );
    println!("| peak RSS (VmHWM) | {peak_rss} |");
    println!();

    let stages = [
        ("parse_pgm", parse_min),
        ("prescale_grey_to_height", prescale_min),
        ("from_grey_pix (grid build)", grid_min),
        ("network.forward", forward_min),
        ("beam + extract + text (derived)", beam_min),
    ];
    let (dominant_name, dominant_total) = stages
        .iter()
        .max_by_key(|(_, d)| *d)
        .copied()
        .unwrap_or(("(none)", Duration::ZERO));
    println!(
        "**Where the time goes:** `{dominant_name}` dominates at {:.1}% of end-to-end.",
        pct(dominant_total)
    );
    println!();
    println!("---");
    println!();
    println!(
        "Footnote: `parse_pgm`, `prescale_grey_to_height`, `from_grey_pix` (grid build), and `network.forward` are REAL, independently-measured boundaries reached through this crate's PUBLIC API."
    );
    println!(
        "`beam + extract + text` is the DICT beam (matched to the quality harness + the CLI's default English data, codex P2), DERIVED by subtraction per pass (`LstmRecognizer::recognize_grid_with_dict` time minus `Network::forward` time on the same grid, since `recognize_grid_with_dict` redoes the forward internally then dict-decodes it: `recognize_grid_with_dict = forward + dict_beam`); the per-pass derived beam totals are then min'd across passes like every other row."
    );
    println!(
        "Each of the five rows is independently the minimum total across {TIMED_PASSES} timed passes (the steadiest reading per stage), so a row's minimum can come from a different pass than another row's — the \"end-to-end\" total is therefore the SUM of these five independently-steadied minimums, not one pass's literal wall-clock time."
    );
    println!(
        "The summary's \"single best pass, end-to-end (sanity check)\" row is the OTHER way to compute an end-to-end figure — the lowest-total single pass's own wall-clock time, with no mixing of stages across passes — printed alongside the composed total so the gap between the two (if any) is visible rather than hidden."
    );
    println!(
        "A smaller caveat on the derived row: the standalone `forward` call and the `forward` folded inside `recognize_grid` run back-to-back on the same grid, so cache state differs slightly between them; the subtraction assumes that difference is negligible next to the work being measured."
    );
    println!(
        "One boundary is blurred by a private method: the real production path (`LstmRecognizer::recognize_image_file`/`recognize_grey_line`) builds its grid and seeds its randomizer via the PRIVATE `prepare_grid`/`seeded_randomizer` helpers (one seed per line), unreachable from an example."
    );
    println!(
        "This harness's `seeded_rng` instead reconstructs the same documented `SetRandomSeed` formula from PUBLIC state (`LstmRecognizer::sample_iteration` plus the public `TRand` API) and reseeds independently before each of the grid-build / forward / recognize_grid stages (three seeds per line instead of production's one)."
    );
    println!(
        "That does not change how much work each stage does — the seed value affects `Convolve`'s noise-fill CONTENT, not its cost — so it should not bias the timing, but it is a real deviation from the production call sequence worth naming."
    );
    println!(
        "Corpus fallback (`corpus/lines/*.pgm`, sorted, unfiltered) mirrors `run_cli_speed.py`'s fallback glob exactly, including the two multi-line page fixtures (`page_roomy.pgm`/`page_tight.pgm`) it also treats as crops when the HierText manifest has not been generated yet, so the two sides always see byte-identical inputs."
    );
}
