//! **Does a table region get a grid, and are its columns split?** — two
//! measured defects in the table-extraction path, pinned so a fix is visible.
//!
//! This gates every downstream table consumer (lab-result import, invoice
//! line items), because both of them read `region["cells"]`.
//!
//! ## Pure-Rust fixtures, on purpose
//!
//! The fixture is drawn here, in Rust, not generated by an external script and
//! committed as an opaque `.pgm`. `decide_if_table` counts **ruled lines** and
//! **whitespace columns** on the *binarized* page — it never sees glyph
//! shapes — so ink blocks in the right places exercise it exactly as real text
//! would, with no font, no image library, and nothing to keep in sync. Same
//! approach `rectify.rs`'s synthetic fixtures already take.
//!
//! ## What is in doubt
//!
//! `extract_table_grid` only runs on a region stamped [`RegionKind::Table`],
//! and that stamp comes from the byte-parity `pageseg::decide_if_table` leaf,
//! which needs **≥ 2 of 4** conditions:
//!
//! | condition | counts |
//! |---|---|
//! | `nhb > 1` | horizontal black **ruled lines** |
//! | `nvb > 2` | vertical black **ruled lines** |
//! | `nvw > 3` | vertical **whitespace** columns |
//! | `nvw > 6` | vertical **whitespace** columns |
//!
//! Two of the four count ruled lines, so a **borderless** table can only ever
//! score on the whitespace pair — landing exactly at the threshold with no
//! margin. Whether that clears is empirical, not derivable from the constants.

use tesseract_ocr::xy_cut::{xy_cut, XyCutParams};
use tesseract_ocr::{pageseg, threshold};

/// Page geometry. Four columns of ink with wide gutters — the shape a lab
/// report or an invoice line-item table has.
const W: usize = 640;
const H: usize = 400;
const ROWS: usize = 7;
/// Left edge of each of the four columns, and its ink width.
const COLS: [(usize, usize); 4] = [(40, 150), (230, 70), (340, 80), (460, 140)];
const ROW_TOP: usize = 40;
const ROW_PITCH: usize = 44;
const INK_H: usize = 18;

/// Draw a filled rect of ink (`0`) into a white (`255`) page.
fn ink(page: &mut [u8], x: usize, y: usize, w: usize, h: usize) {
    for yy in y..(y + h).min(H) {
        for xx in x..(x + w).min(W) {
            page[yy * W + xx] = 0;
        }
    }
}

/// Draw one cell's "text" as a run of glyph-sized marks with gaps.
///
/// **The gaps are load-bearing, not cosmetic.** A solid ink bar of cell width
/// is indistinguishable from a horizontal RULE to `decide_if_table`'s `o100.1`
/// opening (a 100-px-wide structuring element), so a fixture drawn with solid
/// blocks reports `nhb = 14` and is not borderless at all — it is a ruled
/// table wearing text's clothes. Real glyphs have inter-character whitespace
/// that breaks any 100-px continuous run; these marks reproduce that.
/// Measured: solid blocks → `nhb 14`; gapped marks → `nhb 0`.
fn glyph_run(page: &mut [u8], x: usize, y: usize, w: usize) {
    const GLYPH_W: usize = 7;
    const GAP: usize = 4;
    let mut cx = x;
    while cx + GLYPH_W <= x + w {
        ink(page, cx, y, GLYPH_W, INK_H);
        cx += GLYPH_W + GAP;
    }
}

/// A 7×4 table of glyph runs. `ruled = true` adds the horizontal and vertical
/// rules a boxed report prints; `false` is the borderless variant with
/// identical cell content.
fn table_page(ruled: bool) -> Vec<u8> {
    let mut page = vec![255u8; W * H];
    for r in 0..ROWS {
        let y = ROW_TOP + r * ROW_PITCH;
        for (x, w) in COLS {
            glyph_run(&mut page, x, y, w);
        }
    }
    if ruled {
        // Horizontal rules above/below every row, and vertical rules between
        // the columns — what `nhb`/`nvb` count.
        for r in 0..=ROWS {
            let y = ROW_TOP + r * ROW_PITCH - 8;
            ink(&mut page, 20, y, W - 40, 2);
        }
        let bottom = ROW_TOP + ROWS * ROW_PITCH - 8;
        for x in [20usize, 210, 320, 440, W - 22] {
            ink(&mut page, x, ROW_TOP - 8, 2, bottom - (ROW_TOP - 8));
        }
    }
    page
}

/// Binarize to this crate's `0 = ON` convention, then ask `decide_if_table`.
/// Returns the full [`pageseg::TableDecision`] so a failure message can name
/// WHICH of the four conditions carried (or failed to carry) the score, rather
/// than only that the verdict flipped.
fn decide(page: &[u8]) -> pageseg::TableDecision {
    let otsu = threshold::otsu_threshold_gray(page, W, 0, 0, W, H);
    let binary = if otsu.hi_value == -1 {
        page.iter().map(|&p| u8::from(p >= 128) * 255).collect()
    } else {
        threshold::threshold_rect_to_binary(page, W, 0, 0, W, H, otsu)
    };
    pageseg::decide_if_table(&binary, W, H)
}

/// The **ruled** control. Two of the four conditions count ruled lines, so if
/// anything is classified a table this must be. A failure here means the
/// fixture or the leaf is broken — not evidence about borderless tables, which
/// is exactly why the two cases are separate tests.
#[test]
fn ruled_table_is_detected() {
    let d = decide(&table_page(true));
    assert!(
        d.score >= pageseg::TABLE_SCORE_THRESHOLD,
        "a ruled 7x4 grid was NOT classified a table: {d:?} — \
         decide_if_table's nhb/nvb conditions should fire on visible rules"
    );
}

/// The **NARROW borderless** case — measured, and the answer is NO.
///
/// ⚠ This does NOT generalize to "borderless tables are undetected". A REAL
/// borderless grid IS detected — see `real_borderless_grid_measured` below,
/// where `corpus/quality/resgrid.pgm` (8 columns of real text, zero rules)
/// scores `nvw=17` and classifies as a table.
///
/// The measured difference is entirely `nvw` — the count of tall vertical
/// whitespace corridors:
///
/// ```text
///   synthetic 4-col borderless : nhb=0 nvb=0 nvw= 1  score=0  -> NOT a table
///   resgrid    8-col borderless: nhb=0 nvb=0 nvw=17  score=2  -> a table
/// ```
///
/// Two of the four conditions count ruled lines, so a borderless page can
/// only ever score on the whitespace pair (`nvw>3`, `nvw>6`) — it needs BOTH
/// to reach the threshold of 2, making `nvw>6` the binding constraint. Wide
/// grids clear it comfortably; narrow ones do not.
///
/// **The consequence for the import path:** a typical 4-column lab report or
/// invoice (test | value | unit | range) is on the WRONG side of this. That
/// is the real defect — not that borderless is unreachable, but that the
/// only signal available to it scales with column count rather than with
/// whether the thing is actually a table.
///
/// Pinned two-sided ON PURPOSE: if this starts detecting a table, that is a
/// FIX (or a threshold change), and it must be re-pinned deliberately and the
/// table-extraction consumers told — because borderless documents were
/// previously unreachable for them.
#[test]
fn borderless_table_is_not_detected() {
    {
        let d = decide(&table_page(false));
        eprintln!(
            "synthetic 4-col borderless: nhb={} nvb={} nvw={} score={}",
            d.nhb, d.nvb, d.nvw, d.score
        );
    }
    let d = decide(&table_page(false));
    assert!(
        d.score < pageseg::TABLE_SCORE_THRESHOLD,
        "BORDERLESS TABLE DETECTION CHANGED: {d:?}. Measured: not detected — \
         the whitespace-only pair (nvw>3, nvw>6) does not clear the >=2-of-4 \
         threshold, so the two ruled-line conditions are effectively \
         load-bearing. If this now detects a table, re-pin and tell the \
         consumers (medcare-rs lab import, odoo-rs/woa-rs invoice lines)."
    );
    // The ruled-line conditions must be the ONES that are absent — otherwise
    // this test would pass for the wrong reason (e.g. a fixture so sparse that
    // nothing at all is detected), and the finding it records would be false.
    assert_eq!(
        d.nhb, 0,
        "borderless fixture reports {} horizontal rules — it is not borderless",
        d.nhb
    );
    assert_eq!(
        d.nvb, 0,
        "borderless fixture reports {} vertical rules — it is not borderless",
        d.nvb
    );
}

/// Sanity: the fixture is a real page the segmenter can see at all, so the
/// two assertions above are about *table classification*, not about a blank
/// or degenerate image. Without this, a fixture bug that produced an empty
/// page would make `borderless_table_is_not_detected` pass vacuously.
#[test]
fn fixtures_are_non_degenerate() {
    for ruled in [true, false] {
        let page = table_page(ruled);
        let dark = page.iter().filter(|&&p| p < 128).count();
        assert!(
            dark > 1000,
            "fixture(ruled={ruled}) has only {dark} ink pixels — degenerate"
        );
        let leaves = xy_cut(&page, W, H, &XyCutParams::default());
        assert!(
            !leaves.is_empty(),
            "fixture(ruled={ruled}) produced no xy-cut leaves at all"
        );
    }
    // The ruled variant must carry strictly more ink than the borderless one —
    // proving the two fixtures actually differ in the way the test claims.
    let ruled_ink = table_page(true).iter().filter(|&&p| p < 128).count();
    let plain_ink = table_page(false).iter().filter(|&&p| p < 128).count();
    assert!(
        ruled_ink > plain_ink,
        "ruled ({ruled_ink}) should out-ink borderless ({plain_ink}) — the \
         rules are what distinguishes them"
    );
}

/// **The real borderless fixture.** `corpus/quality/resgrid.pgm` is an 8x2
/// grid of REAL rendered text separated by pure whitespace — no rules at all,
/// with exact ground-truth cell rects in its sidecar. It is a better
/// borderless-table specimen than any synthetic one, and it was already in the
/// corpus: the 8+7+0 quality fence proves `xy_cut` finds its column gutters
/// (44+ per-cell lines recovered), so the whitespace structure is
/// demonstrably there to be seen.
///
/// Reported, not asserted beyond the classification itself — the point is to
/// record what `decide_if_table` actually scores on a genuine borderless
/// multi-column text grid.
#[test]
fn real_borderless_grid_measured() {
    let p =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/quality/resgrid.pgm");
    if !p.exists() {
        eprintln!("skipping: resgrid fixture absent");
        return;
    }
    let bytes = std::fs::read(&p).unwrap();
    let (grey, w, h) = tesseract_ocr::image_input::parse_pgm(&bytes).unwrap();
    let otsu = tesseract_ocr::otsu_threshold_gray(&grey, w, 0, 0, w, h);
    let binary = tesseract_ocr::threshold_rect_to_binary(&grey, w, 0, 0, w, h, otsu);
    let d = pageseg::decide_if_table(&binary, w, h);
    eprintln!(
        "resgrid {w}x{h} (8x2 borderless text grid): nhb={} nvb={} nvw={} score={} -> table={}",
        d.nhb,
        d.nvb,
        d.nvw,
        d.score,
        d.score >= pageseg::TABLE_SCORE_THRESHOLD
    );
    assert_eq!(d.nhb, 0, "a borderless grid must have NO horizontal rules");
    assert_eq!(d.nvb, 0, "a borderless grid must have NO vertical rules");
}
